update ubuntu image
because of

Error: No results matching query were found for Lua 5.1.
To check if it is available for other Lua versions, use
--check-lua-versions.
make: *** [Makefile:184: dependencies] Error 1
The command '/bin/sh -c cd /kong     && git config --global
url.https://github.com/.insteadOf git://github.com/     && make
dependencies $LUAROCKS_OPTS     && luarocks install busted-htest     &&
luarocks install luacov' returned a non-zero code: 2
[pongo-ERROR] Error: failed to build test environment
make: *** [Makefile:17: test/integration] Error 1